

ast: 
	gcc -o test ast_test.c ../ast/tree.c ../ast/lex_value.c ../ast/lex_node.c

label: 
	gcc -o test get_label.c ../ast/tree.c ../ast/lex_value.c ../ast/lex_node.c

create_node_with_lex: 
	gcc -o test create_node_with_lex.c ../ast/tree.c ../ast/lex_value.c ../ast/lex_node.c

create_node_with_label: 
	gcc -o test create_node_with_label.c ../ast/tree.c ../ast/lex_value.c ../ast/lex_node.c